const W='/weapons',U='/upgrades',L='/levels',C='/characters',CA='/cars',P='/packs'

export const WEAPONS=[
  {id:1, tier:1,name:'PISTOL',       dmg:1, rate:20,  price:0,     img:`${W}/gun_pistol.jpg`,       color:'gold'  },
  {id:2, tier:1,name:'SHOTGUN',      dmg:3, rate:45,  price:800,   img:`${W}/gun_shotgun.jpg`,      color:'gold'  },
  {id:3, tier:1,name:'LASER',        dmg:2, rate:8,   price:1500,  img:`${W}/gun_laser.jpg`,        color:'cyan'  },
  {id:4, tier:2,name:'ROCKET',       dmg:5, rate:80,  price:3000,  img:`${W}/gun_rocket.jpg`,       color:'cyan'  },
  {id:5, tier:2,name:'PLASMA',       dmg:4, rate:15,  price:5000,  img:`${W}/gun_plasma.jpg`,       color:'purple'},
  {id:6, tier:2,name:'FREEZE RAY',   dmg:2, rate:35,  price:2500,  img:`${W}/gun_freeze.jpg`,       color:'cyan'  },
  {id:7, tier:2,name:'LIGHTNING',    dmg:5, rate:20,  price:4000,  img:`${W}/gun_lightning.jpg`,    color:'cyan'  },
  {id:8, tier:3,name:'RAILGUN',      dmg:8, rate:120, price:8000,  img:`${W}/gun_railgun.jpg`,      color:'purple'},
  {id:9, tier:3,name:'VORTEX',       dmg:4, rate:60,  price:6000,  img:`${W}/gun_vortex.jpg`,       color:'purple'},
  {id:10,tier:3,name:'GRENADE',      dmg:6, rate:90,  price:10000, img:`${W}/gun_grenade.jpg`,      color:'orange'},
  {id:11,tier:3,name:'FLAMETHROWER', dmg:3, rate:5,   price:6000,  img:`${W}/gun_flamethrower.jpg`, color:'orange'},
  {id:12,tier:4,name:'NUKE',         dmg:10,rate:200, price:15000, img:`${W}/gun_nuke.jpg`,         color:'red'   },
  {id:13,tier:2,name:'MACHINE GUN',  dmg:1, rate:3,   price:3000,  img:`${W}/gun_machinegun.jpg`,   color:'gold'  },
  {id:14,tier:5,name:'DEF TOWER',    dmg:4, rate:25,  price:20000, img:`${W}/gun_deftower.jpg`,     color:'purple'},
  {id:15,tier:5,name:'HELICOPTER',   dmg:6, rate:30,  price:25000, img:`${W}/gun_helicopter.jpg`,   color:'cyan'  },
  {id:16,tier:5,name:'ATOMIC BOMB',  dmg:15,rate:300, price:50000, img:`${W}/gun_atomic.jpg`,       color:'red'   },
]

export const UPGRADES=[
  {id:1, cat:'MOVEMENT',name:'TURBO BOOST', effect:'Each level +15% max speed.',          maxLv:5,prices:[100,200,400,800,1600],   img:`${U}/upg_turbo.jpg`,      color:'gold'  },
  {id:2, cat:'MOVEMENT',name:'NITRO BURST', effect:'Speed burst every 20s.',              maxLv:3,prices:[800,1600,3200],          img:`${U}/upg_nitro.jpg`,      color:'cyan'  },
  {id:3, cat:'MOVEMENT',name:'SLIPSTREAM',  effect:'+10% speed on kill for 2s.',          maxLv:3,prices:[700,1400,2800],          img:`${U}/upg_slipstream.jpg`, color:'cyan'  },
  {id:4, cat:'DEFENSE', name:'SHIELD GEN',  effect:'Start with extra shield per level.',  maxLv:5,prices:[300,600,1200,2400,4800], img:`${U}/upg_shield.jpg`,     color:'gold'  },
  {id:5, cat:'DEFENSE', name:'HEAVY ARMOR', effect:'Lv1=25% Lv2=50% Lv3=75% dmg reduce.',maxLv:3,prices:[500,1000,2000],          img:`${U}/upg_armor.jpg`,      color:'gold'  },
  {id:6, cat:'DEFENSE', name:'AUTO REPAIR', effect:'Regen shield every 10s during run.',  maxLv:3,prices:[800,1600,3200],          img:`${U}/upg_autorepair.jpg`, color:'purple'},
  {id:7, cat:'DEFENSE', name:'NANO SHIELD', effect:'Regen 1 shield HP every 5s.',         maxLv:3,prices:[1000,2000,4000],         img:`${U}/upg_nanoshield.jpg`, color:'purple'},
  {id:8, cat:'OFFENSE', name:'RAPID FIRE',  effect:'Each level -10% fire delay.',          maxLv:5,prices:[400,800,1600,3200,6400], img:`${U}/upg_rapidfire.jpg`,  color:'red'   },
  {id:9, cat:'OFFENSE', name:'WAR HEAD',    effect:'+20% bullet damage per level.',       maxLv:5,prices:[600,1200,2400,4800,9600],img:`${U}/upg_warhead.jpg`,    color:'red'   },
  {id:10,cat:'OFFENSE', name:'TWIN SHOT',   effect:'Lv1=2x Lv2=3x Lv3=spread.',          maxLv:3,prices:[1200,2400,4800],         img:`${U}/upg_twinshot.jpg`,   color:'red'   },
  {id:11,cat:'OFFENSE', name:'SCOPE MASTER',effect:'Bullets pierce 1 extra enemy.',       maxLv:3,prices:[900,1800,3600],          img:`${U}/upg_scopemaster.jpg`,color:'gold'  },
  {id:12,cat:'OFFENSE', name:'MINE LAYER',  effect:'Drop mines behind you.',              maxLv:3,prices:[1500,3000,6000],         img:`${U}/upg_minelayer.jpg`,  color:'orange'},
  {id:13,cat:'ECONOMY', name:'COIN MAGNET', effect:'Each level +30px attract radius.',    maxLv:5,prices:[200,400,800,1600,3200],  img:`${U}/upg_magnet.jpg`,     color:'gold'  },
  {id:14,cat:'ECONOMY', name:'DOUBLE COINS',effect:'Earn 2x coins per pickup.',           maxLv:1,prices:[500],                   img:`${U}/upg_doublecoins.jpg`,color:'gold'  },
  {id:15,cat:'ECONOMY', name:'MOTO BOOSTER',effect:'+25% MOTO earned per run.',           maxLv:5,prices:[700,1400,2800,5600,11200],img:`${U}/upg_motobooster.jpg`,color:'cyan' },
  {id:16,cat:'ECONOMY', name:'LUCKY DROPS', effect:'+30% coin drop chance on kill.',      maxLv:3,prices:[600,1200,2400],          img:`${U}/upg_luckydrops.jpg`, color:'green' },
  {id:17,cat:'SURVIVAL',name:'EXTRA LIFE',  effect:'Start with 4 lives instead of 3.',   maxLv:3,prices:[800,1600,3200],          img:`${U}/upg_extralife.jpg`,  color:'red'   },
  {id:18,cat:'SURVIVAL',name:'SECOND WIND', effect:'Auto-revive once per run at 1HP.',    maxLv:1,prices:[3000],                   img:`${U}/upg_secondwind.jpg`, color:'purple'},
  {id:19,cat:'SURVIVAL',name:'STIM PACK',   effect:'First hit heals instead of damages.',maxLv:2,prices:[1800,3600],              img:`${U}/upg_stimpack.jpg`,   color:'green' },
  {id:20,cat:'SPECIAL', name:'HELPER DRONE',effect:'Drone auto-fires at enemies.',        maxLv:3,prices:[2000,4000,8000],         img:`${U}/upg_helperdrone.jpg`,color:'cyan'  },
  {id:21,cat:'SPECIAL', name:'MG TURRET',   effect:'Auto turret fires alongside you.',    maxLv:3,prices:[2500,5000,10000],        img:`${U}/upg_mgturret.jpg`,   color:'purple'},
  {id:22,cat:'SPECIAL', name:'OVERCHARGE',  effect:'10 kills = 5s invincibility.',        maxLv:3,prices:[2500,5000,10000],        img:`${U}/upg_overcharge.jpg`, color:'red'   },
]

export const LEVELS=[
  {id:1, name:'CITY NIGHT',  diff:'EASY',    speed:'1x',   moto:1,   price:0,      img:`${L}/lv1.jpg` },
  {id:2, name:'HIGHWAY',     diff:'EASY+',   speed:'1.2x', moto:2,   price:300,    img:`${L}/lv2.jpg` },
  {id:3, name:'DESERT RUN',  diff:'MEDIUM',  speed:'1.4x', moto:3,   price:600,    img:`${L}/lv3.jpg` },
  {id:4, name:'STORM ZONE',  diff:'MEDIUM',  speed:'1.5x', moto:4,   price:1000,   img:`${L}/lv4.jpg` },
  {id:5, name:'NEON BLADE',  diff:'HARD',    speed:'1.6x', moto:5,   price:1500,   img:`${L}/lv5.jpg` },
  {id:6, name:'ZOMBIE ROAD', diff:'HARD+',   speed:'1.8x', moto:7,   price:2500,   img:`${L}/lv6.jpg` },
  {id:7, name:'MOON BASE',   diff:'INSANE',  speed:'2x',   moto:9,   price:3500,   img:`${L}/lv7.jpg` },
  {id:8, name:'HELL ROAD',   diff:'DEATH',   speed:'2.3x', moto:12,  price:5000,   img:`${L}/lv8.jpg` },
  {id:9, name:'ARCTIC WAR',  diff:'DEATH+',  speed:'2.5x', moto:15,  price:7000,   img:`${L}/lv9.jpg` },
  {id:10,name:'CYBER CITY',  diff:'ULTRA',   speed:'2.8x', moto:18,  price:9000,   img:`${L}/lv10.jpg`},
  {id:11,name:'MONSTER PIT', diff:'ULTRA+',  speed:'3x',   moto:22,  price:12000,  img:`${L}/lv11.jpg`},
  {id:12,name:'VOID ZONE',   diff:'GOD',     speed:'3.2x', moto:27,  price:15000,  img:`${L}/lv12.jpg`},
  {id:13,name:'STORM TITAN', diff:'GOD+',    speed:'3.4x', moto:32,  price:18000,  img:`${L}/lv13.jpg`},
  {id:14,name:'WAR MACHINE', diff:'WAR',     speed:'3.6x', moto:36,  price:22000,  img:`${L}/lv14.jpg`},
  {id:15,name:'ASTRO HELL',  diff:'HELL',    speed:'3.8x', moto:40,  price:28000,  img:`${L}/lv15.jpg`},
  {id:16,name:'MONAD GATE',  diff:'LEGEND',  speed:'4x',   moto:50,  price:35000,  img:`${L}/lv16.jpg`},
  {id:17,name:'PHANTOM CITY',diff:'LEGEND+', speed:'4.3x', moto:60,  price:45000,  img:`${L}/lv17.jpg`},
  {id:18,name:'ATOMIC ZONE', diff:'LEGEND++',speed:'4.6x', moto:75,  price:55000,  img:`${L}/lv18.jpg`},
  {id:19,name:'MONAD CORE',  diff:'ULTIMATE',speed:'5x',   moto:100, price:70000,  img:`${L}/lv19.jpg`},
  {id:20,name:'INFINITE',    diff:'INFINITE',speed:'6x',   moto:200, price:100000, img:`${L}/lv20.jpg`},
]

export const CHARACTERS=[
  {id:1, name:'STREET RIDER', img:`${C}/1caracter.png.jpg`,  price:0,     stat:{spd:6,def:4,lck:5}, color:'gold'  },
  {id:2, name:'DIRT BIKER',   img:`${C}/2caracter.png.jpg`,  price:500,   stat:{spd:7,def:5,lck:4}, color:'gold'  },
  {id:3, name:'NEON GHOST',   img:`${C}/3caracter.png.jpg`,  price:1000,  stat:{spd:8,def:3,lck:6}, color:'cyan'  },
  {id:4, name:'CYBER PHANTOM',img:`${C}/4caracter.png.jpg`,  price:2000,  stat:{spd:9,def:4,lck:5}, color:'purple'},
  {id:5, name:'GOLD GHOST',   img:`${C}/5caracter.png.jpg`,  price:3000,  stat:{spd:8,def:6,lck:7}, color:'gold'  },
  {id:6, name:'SHADOW HACKER',img:`${C}/6caracter.png.jpg`,  price:4000,  stat:{spd:7,def:7,lck:6}, color:'purple'},
  {id:7, name:'NEON RONIN',   img:`${C}/7caracter.png.jpg`,  price:5000,  stat:{spd:9,def:5,lck:8}, color:'cyan'  },
  {id:8, name:'STORM RIDER',  img:`${C}/8caracters.png.jpg`, price:6000,  stat:{spd:10,def:4,lck:6},color:'cyan'  },
  {id:9, name:'VOID WALKER',  img:`${C}/9caracters.png.jpg`, price:8000,  stat:{spd:8,def:8,lck:7}, color:'purple'},
  {id:10,name:'MECH PHANTOM', img:`${C}/10caracters.png.jpg`,price:10000, stat:{spd:7,def:10,lck:5},color:'gold'  },
  {id:11,name:'ATV SAMURAI',  img:`${C}/11caracters.png.jpg`,price:12000, stat:{spd:9,def:7,lck:9}, color:'red'   },
  {id:12,name:'MONAD LEGEND', img:`${C}/12caracters.png.jpg`,price:25000, stat:{spd:10,def:10,lck:10},color:'gold'},
]

export const CARS=[
  {id:1, name:'CAR 1',  img:`${CA}/1.png.jpg`,  price:0,     stat:{spd:6,hdl:5,acc:6}, color:'gold'  },
  {id:2, name:'CAR 2',  img:`${CA}/2.png.jpg`,  price:1000,  stat:{spd:7,hdl:7,acc:5}, color:'cyan'  },
  {id:3, name:'CAR 3',  img:`${CA}/3.png.jpg`,  price:2000,  stat:{spd:7,hdl:6,acc:6}, color:'gold'  },
  {id:4, name:'CAR 4',  img:`${CA}/4.png.jpg`,  price:2500,  stat:{spd:8,hdl:6,acc:7}, color:'cyan'  },
  {id:5, name:'CAR 5',  img:`${CA}/5.png.jpg`,  price:3000,  stat:{spd:8,hdl:7,acc:7}, color:'purple'},
  {id:6, name:'CAR 6',  img:`${CA}/6.png.jpg`,  price:4000,  stat:{spd:9,hdl:5,acc:8}, color:'purple'},
  {id:7, name:'CAR 7',  img:`${CA}/7.png.jpg`,  price:5000,  stat:{spd:9,hdl:6,acc:8}, color:'cyan'  },
  {id:8, name:'CAR 8',  img:`${CA}/8.png.jpg`,  price:6000,  stat:{spd:9,hdl:7,acc:7}, color:'gold'  },
  {id:9, name:'CAR 9',  img:`${CA}/9.png.jpg`,  price:7000,  stat:{spd:10,hdl:6,acc:8},color:'cyan'  },
  {id:10,name:'CAR 10', img:`${CA}/10.png.jpg`, price:8000,  stat:{spd:10,hdl:7,acc:9},color:'purple'},
  {id:11,name:'CAR 11', img:`${CA}/11.png.jpg`, price:10000, stat:{spd:10,hdl:8,acc:9},color:'gold'  },
  {id:12,name:'CAR 12', img:`${CA}/12.png.jpg`, price:15000, stat:{spd:10,hdl:10,acc:10},color:'gold'},
]

export const COIN_PACKS=[
  {id:1,label:'1,000 COINS', price:'$1',  coins:1000,  img:`${P}/pack_micro.jpg`,    color:'gold'  },
  {id:2,label:'2,500 COINS', price:'$2',  coins:2500,  img:`${P}/pack_starter.jpg`,  color:'gold'  },
  {id:3,label:'7,000 COINS', price:'$5',  coins:7000,  img:`${P}/pack_racer.jpg`,    color:'cyan'  },
  {id:4,label:'15,000 COINS',price:'$10', coins:15000, img:`${P}/pack_fighter.jpg`,  color:'cyan'  },
  {id:5,label:'35,000 COINS',price:'$20', coins:35000, img:`${P}/pack_champion.jpg`, color:'purple'},
  {id:6,label:'100,000 COINS',price:'$50',coins:100000,img:`${P}/pack_elite.jpg`,    color:'purple'},
  {id:7,label:'250,000 COINS',price:'$100',coins:250000,img:`${P}/pack_whale.jpg`,   color:'gold'  },
]
